//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Finale3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD
    {
        public int ID { get; set; }
        public string Category { get; set; }
        public string Title { get; set; }
        public Nullable<int> Price { get; set; }
        public string Param1 { get; set; }
        public string Param2 { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Location { get; set; }
    }
}
